### ISSUE TITLE
gabaB units wrong

### ISSUE THREAD

**Issue by erik-roberts** [asoplata/ching2010_tcre_dynasim_mechanisms#3]
gabaB has units in mM for k's, but uM for kD.

**Comment by asoplata** [comment]
There is no error here.

Going from the (Destexhe et al., 1996) paper, of the numbered K rate constants, *only* K1 is in units of mM^-1 or any other concentration. K1 is only utilized in dR/dt, and K1 is supposed to be in mM^-1 because it is multipled by [T], which is in mM. I believe R itself, like D, is unitless.

dR/dt = K1 * T * (1-R-D) - K2 * R

G, weirdly, is not unitless but yes, is in units of uM, not mM. However, the ODE for it

dG/dt = K3 * R - K4 * G

Only relies on K3 and K4, both of which are only in ms^-1, and the unitless R. Therefore, G never directly interacts with any mM terms, and is free to be in units of uM. Both G and KD are in units of uM and so they are fine, and they never directly interacts with the mM^-1 term of K1. Therefore, there's not problem here, at least with the implementation. I use the same or almost the same numbers for all five K values as the paper's original code, which also doesn't change any of the numbers from the paper itself (for this current).

Yes, they're mixing unitless and uM terms in dG/dt, but if that's a real problem, it's a problem with the model, not the implementation, since our implementations are the same. I suspect this isn't a major problem with this GABAB model, though.

**Comment by erik-roberts** [comment]
one cannot mix unitless with unit numbers afaik. so i think the interpretation needs to reflect that r has units that match g.

**Comment by asoplata** [comment]
Yeah, I agree -- but the problem is not uM vs mM, it's basically unitless vs uM. So all the numbers/values are correct, but it's more the *model equations*/formulation that may have issues. I don't think this makes the model useless, though.
